appversion: v1
kind: deployment
metadata:
  name: backend_deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          build: ./backend
          ports:
            - containerPort: 3001
