appversion: v1
kind: deployment
metadata:
  name: frontend_frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          build: ./frontend
          ports:
            - containerPort: 3000